# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaseHistory.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 842)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_5.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_HistoryNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_HistoryNumber.setObjectName("label_HistoryNumber")
        self.gridLayout_5.addWidget(self.label_HistoryNumber, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_MoveFrom = QtWidgets.QLabel(self.centralwidget)
        self.label_MoveFrom.setObjectName("label_MoveFrom")
        self.horizontalLayout.addWidget(self.label_MoveFrom)
        self.comboBox_MoveFromOrganization = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_MoveFromOrganization.setObjectName("comboBox_MoveFromOrganization")
        self.comboBox_MoveFromOrganization.addItem("")
        self.comboBox_MoveFromOrganization.setItemText(0, "")
        self.comboBox_MoveFromOrganization.addItem("")
        self.comboBox_MoveFromOrganization.addItem("")
        self.comboBox_MoveFromOrganization.addItem("")
        self.comboBox_MoveFromOrganization.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_MoveFromOrganization)
        self.label_MoveFromDepartment = QtWidgets.QLabel(self.centralwidget)
        self.label_MoveFromDepartment.setObjectName("label_MoveFromDepartment")
        self.horizontalLayout.addWidget(self.label_MoveFromDepartment)
        self.lineEdit_MoveFromDepartment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MoveFromDepartment.setObjectName("lineEdit_MoveFromDepartment")
        self.horizontalLayout.addWidget(self.lineEdit_MoveFromDepartment)
        self.label_MoveFromDoctor = QtWidgets.QLabel(self.centralwidget)
        self.label_MoveFromDoctor.setObjectName("label_MoveFromDoctor")
        self.horizontalLayout.addWidget(self.label_MoveFromDoctor)
        self.lineEdit_MoveFromDoctor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MoveFromDoctor.setObjectName("lineEdit_MoveFromDoctor")
        self.horizontalLayout.addWidget(self.lineEdit_MoveFromDoctor)
        self.dateTimeEdit_MoveFromDateTime = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_MoveFromDateTime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 25, 0)))
        self.dateTimeEdit_MoveFromDateTime.setTime(QtCore.QTime(10, 25, 0))
        self.dateTimeEdit_MoveFromDateTime.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateTimeEdit_MoveFromDateTime.setCalendarPopup(True)
        self.dateTimeEdit_MoveFromDateTime.setObjectName("dateTimeEdit_MoveFromDateTime")
        self.horizontalLayout.addWidget(self.dateTimeEdit_MoveFromDateTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_CurrentDoctor = QtWidgets.QLabel(self.centralwidget)
        self.label_CurrentDoctor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CurrentDoctor.setObjectName("label_CurrentDoctor")
        self.horizontalLayout_3.addWidget(self.label_CurrentDoctor)
        self.comboBox_CurrentDoctor = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_CurrentDoctor.setObjectName("comboBox_CurrentDoctor")
        self.comboBox_CurrentDoctor.addItem("")
        self.comboBox_CurrentDoctor.setItemText(0, "")
        self.comboBox_CurrentDoctor.addItem("")
        self.comboBox_CurrentDoctor.addItem("")
        self.comboBox_CurrentDoctor.addItem("")
        self.comboBox_CurrentDoctor.addItem("")
        self.comboBox_CurrentDoctor.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_CurrentDoctor)
        self.label_DaysInOIOPP = QtWidgets.QLabel(self.centralwidget)
        self.label_DaysInOIOPP.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DaysInOIOPP.setObjectName("label_DaysInOIOPP")
        self.horizontalLayout_3.addWidget(self.label_DaysInOIOPP)
        self.lineEdit_DaysInOIOPP = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DaysInOIOPP.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_DaysInOIOPP.setObjectName("lineEdit_DaysInOIOPP")
        self.horizontalLayout_3.addWidget(self.lineEdit_DaysInOIOPP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_MovTo = QtWidgets.QLabel(self.centralwidget)
        self.label_MovTo.setObjectName("label_MovTo")
        self.horizontalLayout_2.addWidget(self.label_MovTo)
        self.comboBox_MoveToOrganization = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_MoveToOrganization.setObjectName("comboBox_MoveToOrganization")
        self.comboBox_MoveToOrganization.addItem("")
        self.comboBox_MoveToOrganization.setItemText(0, "")
        self.comboBox_MoveToOrganization.addItem("")
        self.comboBox_MoveToOrganization.addItem("")
        self.comboBox_MoveToOrganization.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_MoveToOrganization)
        self.label_MoveToDepartment = QtWidgets.QLabel(self.centralwidget)
        self.label_MoveToDepartment.setObjectName("label_MoveToDepartment")
        self.horizontalLayout_2.addWidget(self.label_MoveToDepartment)
        self.lineEdit_MoveToDepatment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MoveToDepatment.setObjectName("lineEdit_MoveToDepatment")
        self.horizontalLayout_2.addWidget(self.lineEdit_MoveToDepatment)
        self.label_MoveToDoctor = QtWidgets.QLabel(self.centralwidget)
        self.label_MoveToDoctor.setObjectName("label_MoveToDoctor")
        self.horizontalLayout_2.addWidget(self.label_MoveToDoctor)
        self.lineEdit_MoveToDoctor = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MoveToDoctor.setObjectName("lineEdit_MoveToDoctor")
        self.horizontalLayout_2.addWidget(self.lineEdit_MoveToDoctor)
        self.dateEdit_MoveToDate = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_MoveToDate.setCalendarPopup(True)
        self.dateEdit_MoveToDate.setObjectName("dateEdit_MoveToDate")
        self.horizontalLayout_2.addWidget(self.dateEdit_MoveToDate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 5, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 0, 4, 1, 1)
        self.lineEdit_YearOfHistory = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_YearOfHistory.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_YearOfHistory.setObjectName("lineEdit_YearOfHistory")
        self.gridLayout_5.addWidget(self.lineEdit_YearOfHistory, 0, 3, 1, 1)
        self.lineEdit_HistoryNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_HistoryNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_HistoryNumber.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_HistoryNumber.setObjectName("lineEdit_HistoryNumber")
        self.gridLayout_5.addWidget(self.lineEdit_HistoryNumber, 0, 1, 1, 1)
        self.label_Slash = QtWidgets.QLabel(self.centralwidget)
        self.label_Slash.setObjectName("label_Slash")
        self.gridLayout_5.addWidget(self.label_Slash, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_PatientLastName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PatientLastName.setStyleSheet("background-color: rgb(238, 255, 190);")
        self.lineEdit_PatientLastName.setObjectName("lineEdit_PatientLastName")
        self.gridLayout_4.addWidget(self.lineEdit_PatientLastName, 2, 1, 1, 1)
        self.label_PatientLastName = QtWidgets.QLabel(self.centralwidget)
        self.label_PatientLastName.setObjectName("label_PatientLastName")
        self.gridLayout_4.addWidget(self.label_PatientLastName, 2, 0, 1, 1)
        self.lineEdit_PatientPatronymic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PatientPatronymic.setStyleSheet("background-color: rgb(238, 255, 190);")
        self.lineEdit_PatientPatronymic.setObjectName("lineEdit_PatientPatronymic")
        self.gridLayout_4.addWidget(self.lineEdit_PatientPatronymic, 2, 5, 1, 1)
        self.label_PatientBirthDate = QtWidgets.QLabel(self.centralwidget)
        self.label_PatientBirthDate.setObjectName("label_PatientBirthDate")
        self.gridLayout_4.addWidget(self.label_PatientBirthDate, 5, 0, 1, 1)
        self.label_PatientPatronymic = QtWidgets.QLabel(self.centralwidget)
        self.label_PatientPatronymic.setObjectName("label_PatientPatronymic")
        self.gridLayout_4.addWidget(self.label_PatientPatronymic, 2, 4, 1, 1)
        self.label_TypeOFObservation = QtWidgets.QLabel(self.centralwidget)
        self.label_TypeOFObservation.setObjectName("label_TypeOFObservation")
        self.gridLayout_4.addWidget(self.label_TypeOFObservation, 5, 4, 1, 1)
        self.lineEdit_OmsID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OmsID.setObjectName("lineEdit_OmsID")
        self.gridLayout_4.addWidget(self.lineEdit_OmsID, 3, 5, 1, 1)
        self.label_FLGDate = QtWidgets.QLabel(self.centralwidget)
        self.label_FLGDate.setObjectName("label_FLGDate")
        self.gridLayout_4.addWidget(self.label_FLGDate, 6, 0, 1, 1)
        self.label_PassportID = QtWidgets.QLabel(self.centralwidget)
        self.label_PassportID.setObjectName("label_PassportID")
        self.gridLayout_4.addWidget(self.label_PassportID, 3, 0, 1, 1)
        self.lineEdit_SnilsID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SnilsID.setObjectName("lineEdit_SnilsID")
        self.gridLayout_4.addWidget(self.lineEdit_SnilsID, 3, 3, 1, 1)
        self.dateEdit_PatientBirthDate = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_PatientBirthDate.setCalendarPopup(True)
        self.dateEdit_PatientBirthDate.setObjectName("dateEdit_PatientBirthDate")
        self.gridLayout_4.addWidget(self.dateEdit_PatientBirthDate, 5, 1, 1, 1)
        self.label_PatientFirstName = QtWidgets.QLabel(self.centralwidget)
        self.label_PatientFirstName.setObjectName("label_PatientFirstName")
        self.gridLayout_4.addWidget(self.label_PatientFirstName, 2, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_DrugIntolerance = QtWidgets.QLabel(self.centralwidget)
        self.label_DrugIntolerance.setObjectName("label_DrugIntolerance")
        self.horizontalLayout_5.addWidget(self.label_DrugIntolerance)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.lineEdit_DrugIntolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DrugIntolerance.setObjectName("lineEdit_DrugIntolerance")
        self.verticalLayout_3.addWidget(self.lineEdit_DrugIntolerance)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 5, 3, 1, 1)
        self.label_SnilsID = QtWidgets.QLabel(self.centralwidget)
        self.label_SnilsID.setObjectName("label_SnilsID")
        self.gridLayout_4.addWidget(self.label_SnilsID, 3, 2, 1, 1)
        self.lineEdit_PassportID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PassportID.setObjectName("lineEdit_PassportID")
        self.gridLayout_4.addWidget(self.lineEdit_PassportID, 3, 1, 1, 1)
        self.lineEdit_PatientFirstName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PatientFirstName.setStyleSheet("background-color: rgb(238, 255, 190);")
        self.lineEdit_PatientFirstName.setObjectName("lineEdit_PatientFirstName")
        self.gridLayout_4.addWidget(self.lineEdit_PatientFirstName, 2, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_TypeK = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TypeK.setObjectName("radioButton_TypeK")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_TypeK)
        self.gridLayout.addWidget(self.radioButton_TypeK, 0, 0, 1, 1)
        self.radioButton_TypeADN = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TypeADN.setObjectName("radioButton_TypeADN")
        self.buttonGroup_2.addButton(self.radioButton_TypeADN)
        self.gridLayout.addWidget(self.radioButton_TypeADN, 1, 0, 1, 1)
        self.radioButton_TypeD = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TypeD.setObjectName("radioButton_TypeD")
        self.buttonGroup_2.addButton(self.radioButton_TypeD)
        self.gridLayout.addWidget(self.radioButton_TypeD, 0, 1, 1, 1)
        self.radioButton_TypeUnknown = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TypeUnknown.setChecked(True)
        self.radioButton_TypeUnknown.setObjectName("radioButton_TypeUnknown")
        self.buttonGroup_2.addButton(self.radioButton_TypeUnknown)
        self.gridLayout.addWidget(self.radioButton_TypeUnknown, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 5, 5, 1, 1)
        self.label_OmsID = QtWidgets.QLabel(self.centralwidget)
        self.label_OmsID.setObjectName("label_OmsID")
        self.gridLayout_4.addWidget(self.label_OmsID, 3, 4, 1, 1)
        self.dateEdit_FLGDate = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_FLGDate.setCalendarPopup(True)
        self.dateEdit_FLGDate.setObjectName("dateEdit_FLGDate")
        self.gridLayout_4.addWidget(self.dateEdit_FLGDate, 6, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_Male = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Male.setObjectName("radioButton_Male")
        self.verticalLayout_5.addWidget(self.radioButton_Male)
        self.radioButton_Female = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_Female.setObjectName("radioButton_Female")
        self.verticalLayout_5.addWidget(self.radioButton_Female)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 5, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_WorkStatus = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_WorkStatus.setObjectName("comboBox_WorkStatus")
        self.comboBox_WorkStatus.addItem("")
        self.comboBox_WorkStatus.addItem("")
        self.comboBox_WorkStatus.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_WorkStatus)
        self.label_WorkStudy = QtWidgets.QLabel(self.centralwidget)
        self.label_WorkStudy.setObjectName("label_WorkStudy")
        self.horizontalLayout_7.addWidget(self.label_WorkStudy)
        self.lineEdit_WorkStudy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_WorkStudy.setObjectName("lineEdit_WorkStudy")
        self.horizontalLayout_7.addWidget(self.lineEdit_WorkStudy)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_MobilityGroup = QtWidgets.QLabel(self.centralwidget)
        self.label_MobilityGroup.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_MobilityGroup.setWordWrap(True)
        self.label_MobilityGroup.setObjectName("label_MobilityGroup")
        self.horizontalLayout_9.addWidget(self.label_MobilityGroup)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.radioButton_GroupM1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_GroupM1.setChecked(True)
        self.radioButton_GroupM1.setObjectName("radioButton_GroupM1")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_GroupM1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_GroupM1)
        self.label_GroupM1 = QtWidgets.QLabel(self.centralwidget)
        self.label_GroupM1.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_GroupM1.setWordWrap(True)
        self.label_GroupM1.setObjectName("label_GroupM1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_GroupM1)
        self.radioButton_GroupM2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_GroupM2.setObjectName("radioButton_GroupM2")
        self.buttonGroup_4.addButton(self.radioButton_GroupM2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_GroupM2)
        self.label_GroupM2 = QtWidgets.QLabel(self.centralwidget)
        self.label_GroupM2.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_GroupM2.setLineWidth(1)
        self.label_GroupM2.setTextFormat(QtCore.Qt.PlainText)
        self.label_GroupM2.setScaledContents(True)
        self.label_GroupM2.setWordWrap(True)
        self.label_GroupM2.setObjectName("label_GroupM2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_GroupM2)
        self.radioButton_GroupM3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_GroupM3.setObjectName("radioButton_GroupM3")
        self.buttonGroup_4.addButton(self.radioButton_GroupM3)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_GroupM3)
        self.label_GroupM3 = QtWidgets.QLabel(self.centralwidget)
        self.label_GroupM3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_GroupM3.setWordWrap(True)
        self.label_GroupM3.setObjectName("label_GroupM3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_GroupM3)
        self.radioButton_GroupM4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_GroupM4.setObjectName("radioButton_GroupM4")
        self.buttonGroup_4.addButton(self.radioButton_GroupM4)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioButton_GroupM4)
        self.label_GroupM4 = QtWidgets.QLabel(self.centralwidget)
        self.label_GroupM4.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_GroupM4.setWordWrap(True)
        self.label_GroupM4.setObjectName("label_GroupM4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_GroupM4)
        self.radioButton_GroupImmobile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_GroupImmobile.setObjectName("radioButton_GroupImmobile")
        self.buttonGroup_4.addButton(self.radioButton_GroupImmobile)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.radioButton_GroupImmobile)
        self.label_GroupImmobile = QtWidgets.QLabel(self.centralwidget)
        self.label_GroupImmobile.setMaximumSize(QtCore.QSize(800, 16777215))
        self.label_GroupImmobile.setWordWrap(True)
        self.label_GroupImmobile.setObjectName("label_GroupImmobile")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_GroupImmobile)
        self.horizontalLayout_9.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_DisabilityGroup = QtWidgets.QLabel(self.centralwidget)
        self.label_DisabilityGroup.setObjectName("label_DisabilityGroup")
        self.horizontalLayout_4.addWidget(self.label_DisabilityGroup)
        self.radioButton_DisabilityGroup0 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DisabilityGroup0.setAutoExclusive(True)
        self.radioButton_DisabilityGroup0.setObjectName("radioButton_DisabilityGroup0")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_DisabilityGroup0)
        self.horizontalLayout_4.addWidget(self.radioButton_DisabilityGroup0)
        self.radioButton_DisabilityGroupUnknown = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DisabilityGroupUnknown.setMouseTracking(False)
        self.radioButton_DisabilityGroupUnknown.setCheckable(True)
        self.radioButton_DisabilityGroupUnknown.setChecked(True)
        self.radioButton_DisabilityGroupUnknown.setAutoExclusive(True)
        self.radioButton_DisabilityGroupUnknown.setObjectName("radioButton_DisabilityGroupUnknown")
        self.buttonGroup_3.addButton(self.radioButton_DisabilityGroupUnknown)
        self.horizontalLayout_4.addWidget(self.radioButton_DisabilityGroupUnknown)
        self.radioButton_DisabilityGroup1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DisabilityGroup1.setAutoExclusive(True)
        self.radioButton_DisabilityGroup1.setObjectName("radioButton_DisabilityGroup1")
        self.buttonGroup_3.addButton(self.radioButton_DisabilityGroup1)
        self.horizontalLayout_4.addWidget(self.radioButton_DisabilityGroup1)
        self.radioButton_DisabilityGroup2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DisabilityGroup2.setAutoExclusive(True)
        self.radioButton_DisabilityGroup2.setObjectName("radioButton_DisabilityGroup2")
        self.buttonGroup_3.addButton(self.radioButton_DisabilityGroup2)
        self.horizontalLayout_4.addWidget(self.radioButton_DisabilityGroup2)
        self.radioButton_DisabilityGroup3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_DisabilityGroup3.setAutoExclusive(True)
        self.radioButton_DisabilityGroup3.setObjectName("radioButton_DisabilityGroup3")
        self.buttonGroup_3.addButton(self.radioButton_DisabilityGroup3)
        self.horizontalLayout_4.addWidget(self.radioButton_DisabilityGroup3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_Building = QtWidgets.QLabel(self.centralwidget)
        self.label_Building.setObjectName("label_Building")
        self.gridLayout_6.addWidget(self.label_Building, 0, 6, 1, 1)
        self.comboBox_TypeOfRoadMain = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_TypeOfRoadMain.setObjectName("comboBox_TypeOfRoadMain")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.comboBox_TypeOfRoadMain.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_TypeOfRoadMain, 0, 2, 1, 1)
        self.lineEdit_RoadMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_RoadMain.setObjectName("lineEdit_RoadMain")
        self.gridLayout_6.addWidget(self.lineEdit_RoadMain, 0, 3, 1, 1)
        self.lineEdit_BuildingMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_BuildingMain.setObjectName("lineEdit_BuildingMain")
        self.gridLayout_6.addWidget(self.lineEdit_BuildingMain, 0, 7, 1, 1)
        self.label_Home = QtWidgets.QLabel(self.centralwidget)
        self.label_Home.setObjectName("label_Home")
        self.gridLayout_6.addWidget(self.label_Home, 0, 4, 1, 1)
        self.lineEdit_ApartmentNumberMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ApartmentNumberMain.setObjectName("lineEdit_ApartmentNumberMain")
        self.gridLayout_6.addWidget(self.lineEdit_ApartmentNumberMain, 0, 9, 1, 1)
        self.label_ApartmentNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_ApartmentNumber.setObjectName("label_ApartmentNumber")
        self.gridLayout_6.addWidget(self.label_ApartmentNumber, 0, 8, 1, 1)
        self.label_CurrentAdress = QtWidgets.QLabel(self.centralwidget)
        self.label_CurrentAdress.setObjectName("label_CurrentAdress")
        self.gridLayout_6.addWidget(self.label_CurrentAdress, 0, 0, 1, 1)
        self.lineEdit_CityMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CityMain.setObjectName("lineEdit_CityMain")
        self.gridLayout_6.addWidget(self.lineEdit_CityMain, 0, 1, 1, 1)
        self.lineEdit_HomeMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_HomeMain.setObjectName("lineEdit_HomeMain")
        self.gridLayout_6.addWidget(self.lineEdit_HomeMain, 0, 5, 1, 1)
        self.label_Entrance = QtWidgets.QLabel(self.centralwidget)
        self.label_Entrance.setObjectName("label_Entrance")
        self.gridLayout_6.addWidget(self.label_Entrance, 1, 0, 1, 1)
        self.label_AdressOfRegistration = QtWidgets.QLabel(self.centralwidget)
        self.label_AdressOfRegistration.setObjectName("label_AdressOfRegistration")
        self.gridLayout_6.addWidget(self.label_AdressOfRegistration, 2, 0, 1, 1)
        self.lineEdit_EntranceMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EntranceMain.setObjectName("lineEdit_EntranceMain")
        self.gridLayout_6.addWidget(self.lineEdit_EntranceMain, 1, 1, 1, 1)
        self.lineEdit_CityReg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CityReg.setText("")
        self.lineEdit_CityReg.setObjectName("lineEdit_CityReg")
        self.gridLayout_6.addWidget(self.lineEdit_CityReg, 2, 1, 1, 1)
        self.label_Floor = QtWidgets.QLabel(self.centralwidget)
        self.label_Floor.setObjectName("label_Floor")
        self.gridLayout_6.addWidget(self.label_Floor, 1, 2, 1, 1)
        self.comboBox_TypeOfRoadReg = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_TypeOfRoadReg.setObjectName("comboBox_TypeOfRoadReg")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.comboBox_TypeOfRoadReg.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_TypeOfRoadReg, 2, 2, 1, 1)
        self.lineEdit_FloorMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FloorMain.setObjectName("lineEdit_FloorMain")
        self.gridLayout_6.addWidget(self.lineEdit_FloorMain, 1, 3, 1, 1)
        self.lineEdit_RoadReg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_RoadReg.setObjectName("lineEdit_RoadReg")
        self.gridLayout_6.addWidget(self.lineEdit_RoadReg, 2, 3, 1, 1)
        self.label_CodeMain = QtWidgets.QLabel(self.centralwidget)
        self.label_CodeMain.setObjectName("label_CodeMain")
        self.gridLayout_6.addWidget(self.label_CodeMain, 1, 4, 1, 1)
        self.label_HomeReg = QtWidgets.QLabel(self.centralwidget)
        self.label_HomeReg.setObjectName("label_HomeReg")
        self.gridLayout_6.addWidget(self.label_HomeReg, 2, 4, 1, 1)
        self.lineEdit_HomeReg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_HomeReg.setObjectName("lineEdit_HomeReg")
        self.gridLayout_6.addWidget(self.lineEdit_HomeReg, 2, 5, 1, 1)
        self.label_BuildingReg = QtWidgets.QLabel(self.centralwidget)
        self.label_BuildingReg.setObjectName("label_BuildingReg")
        self.gridLayout_6.addWidget(self.label_BuildingReg, 2, 6, 1, 1)
        self.lineEdit_BuildingReg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_BuildingReg.setObjectName("lineEdit_BuildingReg")
        self.gridLayout_6.addWidget(self.lineEdit_BuildingReg, 2, 7, 1, 1)
        self.label_ApartmentNumberReg = QtWidgets.QLabel(self.centralwidget)
        self.label_ApartmentNumberReg.setObjectName("label_ApartmentNumberReg")
        self.gridLayout_6.addWidget(self.label_ApartmentNumberReg, 2, 8, 1, 1)
        self.lineEdit_ApartmentNumberReg = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ApartmentNumberReg.setObjectName("lineEdit_ApartmentNumberReg")
        self.gridLayout_6.addWidget(self.lineEdit_ApartmentNumberReg, 2, 9, 1, 1)
        self.lineEdit_MobilePhoneNumberMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MobilePhoneNumberMain.setText("")
        self.lineEdit_MobilePhoneNumberMain.setObjectName("lineEdit_MobilePhoneNumberMain")
        self.gridLayout_6.addWidget(self.lineEdit_MobilePhoneNumberMain, 1, 9, 1, 1)
        self.label_MobilePhoneNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_MobilePhoneNumber.setObjectName("label_MobilePhoneNumber")
        self.gridLayout_6.addWidget(self.label_MobilePhoneNumber, 1, 8, 1, 1)
        self.lineEdit_HomeTelephoneNumberMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_HomeTelephoneNumberMain.setText("")
        self.lineEdit_HomeTelephoneNumberMain.setObjectName("lineEdit_HomeTelephoneNumberMain")
        self.gridLayout_6.addWidget(self.lineEdit_HomeTelephoneNumberMain, 1, 7, 1, 1)
        self.label_HomeTelephoneNumber = QtWidgets.QLabel(self.centralwidget)
        self.label_HomeTelephoneNumber.setObjectName("label_HomeTelephoneNumber")
        self.gridLayout_6.addWidget(self.label_HomeTelephoneNumber, 1, 6, 1, 1)
        self.lineEdit_CodeMain = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CodeMain.setObjectName("lineEdit_CodeMain")
        self.gridLayout_6.addWidget(self.lineEdit_CodeMain, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_ProxyTelephoneNumber2 = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyTelephoneNumber2.setObjectName("label_ProxyTelephoneNumber2")
        self.gridLayout_8.addWidget(self.label_ProxyTelephoneNumber2, 1, 3, 1, 1)
        self.lineEdit_ProxyFirstName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyFirstName.setObjectName("lineEdit_ProxyFirstName")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyFirstName, 0, 4, 1, 1)
        self.label_ProxyPatronymic = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyPatronymic.setObjectName("label_ProxyPatronymic")
        self.gridLayout_8.addWidget(self.label_ProxyPatronymic, 0, 5, 1, 1)
        self.label_ProxyFirstName = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyFirstName.setObjectName("label_ProxyFirstName")
        self.gridLayout_8.addWidget(self.label_ProxyFirstName, 0, 3, 1, 1)
        self.label_ProxyTelephoneNumber1 = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyTelephoneNumber1.setObjectName("label_ProxyTelephoneNumber1")
        self.gridLayout_8.addWidget(self.label_ProxyTelephoneNumber1, 1, 1, 1, 1)
        self.lineEdit_ProxyTelephoneNumber3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyTelephoneNumber3.setText("")
        self.lineEdit_ProxyTelephoneNumber3.setObjectName("lineEdit_ProxyTelephoneNumber3")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyTelephoneNumber3, 1, 6, 1, 1)
        self.lineEdit_ProxyTelephoneNumber2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyTelephoneNumber2.setText("")
        self.lineEdit_ProxyTelephoneNumber2.setObjectName("lineEdit_ProxyTelephoneNumber2")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyTelephoneNumber2, 1, 4, 1, 1)
        self.lineEdit_ProxyLastName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyLastName.setObjectName("lineEdit_ProxyLastName")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyLastName, 0, 2, 1, 1)
        self.lineEdit_ProxyPatronymic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyPatronymic.setObjectName("lineEdit_ProxyPatronymic")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyPatronymic, 0, 6, 1, 1)
        self.comboBox_ProxyType = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ProxyType.setObjectName("comboBox_ProxyType")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.setItemText(0, "")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.comboBox_ProxyType.addItem("")
        self.gridLayout_8.addWidget(self.comboBox_ProxyType, 0, 0, 1, 1)
        self.label_ProxyLastName = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyLastName.setObjectName("label_ProxyLastName")
        self.gridLayout_8.addWidget(self.label_ProxyLastName, 0, 1, 1, 1)
        self.lineEdit_ProxyTelephoneNumber1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyTelephoneNumber1.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_ProxyTelephoneNumber1.setText("")
        self.lineEdit_ProxyTelephoneNumber1.setObjectName("lineEdit_ProxyTelephoneNumber1")
        self.gridLayout_8.addWidget(self.lineEdit_ProxyTelephoneNumber1, 1, 2, 1, 1)
        self.label_ProxyTelephoneNumber3 = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyTelephoneNumber3.setObjectName("label_ProxyTelephoneNumber3")
        self.gridLayout_8.addWidget(self.label_ProxyTelephoneNumber3, 1, 5, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ProxyCommentaries = QtWidgets.QLabel(self.centralwidget)
        self.label_ProxyCommentaries.setObjectName("label_ProxyCommentaries")
        self.horizontalLayout_6.addWidget(self.label_ProxyCommentaries)
        self.lineEdit_ProxyCommentaries = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ProxyCommentaries.setObjectName("lineEdit_ProxyCommentaries")
        self.horizontalLayout_6.addWidget(self.lineEdit_ProxyCommentaries)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 2, 0, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_ReabilitationFamily = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationFamily.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationFamily.setObjectName("checkBox_ReabilitationFamily")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationFamily, 1, 1, 1, 1)
        self.checkBox_ReabilitationMotivation = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationMotivation.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationMotivation.setObjectName("checkBox_ReabilitationMotivation")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationMotivation, 1, 3, 1, 1)
        self.radioButton_TreatmentMotivationMedium = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TreatmentMotivationMedium.setStyleSheet("background-color: rgb(255, 221, 230);")
        self.radioButton_TreatmentMotivationMedium.setObjectName("radioButton_TreatmentMotivationMedium")
        self.buttonGroup_7 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName("buttonGroup_7")
        self.buttonGroup_7.addButton(self.radioButton_TreatmentMotivationMedium)
        self.gridLayout_7.addWidget(self.radioButton_TreatmentMotivationMedium, 4, 2, 1, 1)
        self.label_TreatmentAttitude = QtWidgets.QLabel(self.centralwidget)
        self.label_TreatmentAttitude.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.label_TreatmentAttitude.setWordWrap(True)
        self.label_TreatmentAttitude.setObjectName("label_TreatmentAttitude")
        self.gridLayout_7.addWidget(self.label_TreatmentAttitude, 2, 0, 1, 1)
        self.label_TreatmentMotivation = QtWidgets.QLabel(self.centralwidget)
        self.label_TreatmentMotivation.setStyleSheet("background-color: rgb(255, 221, 230);")
        self.label_TreatmentMotivation.setWordWrap(True)
        self.label_TreatmentMotivation.setObjectName("label_TreatmentMotivation")
        self.gridLayout_7.addWidget(self.label_TreatmentMotivation, 4, 0, 1, 1)
        self.checkBox_ReabilitationIndividual = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationIndividual.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationIndividual.setObjectName("checkBox_ReabilitationIndividual")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationIndividual, 1, 0, 1, 1)
        self.checkBox_TreatmentAttitudeNegativity = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeNegativity.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeNegativity.setObjectName("checkBox_TreatmentAttitudeNegativity")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeNegativity, 3, 2, 1, 1)
        self.checkBox_TreatmentAttitudeNeutral = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeNeutral.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeNeutral.setObjectName("checkBox_TreatmentAttitudeNeutral")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeNeutral, 2, 2, 1, 1)
        self.checkBox_TreatmentAttitudePassive = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudePassive.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudePassive.setObjectName("checkBox_TreatmentAttitudePassive")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudePassive, 2, 3, 1, 1)
        self.checkBox_TreatmentAttitudeIndifferent = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeIndifferent.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeIndifferent.setObjectName("checkBox_TreatmentAttitudeIndifferent")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeIndifferent, 3, 1, 1, 1)
        self.radioButton_ReabilitationLow = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ReabilitationLow.setStyleSheet("background-color: rgb(247, 224, 255);")
        self.radioButton_ReabilitationLow.setObjectName("radioButton_ReabilitationLow")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.radioButton_ReabilitationLow)
        self.gridLayout_7.addWidget(self.radioButton_ReabilitationLow, 0, 3, 1, 1)
        self.checkBox_ReabilitationTBN = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationTBN.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationTBN.setChecked(True)
        self.checkBox_ReabilitationTBN.setObjectName("checkBox_ReabilitationTBN")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationTBN, 1, 4, 1, 1)
        self.checkBox_TreatmentAttitudeActive = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeActive.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeActive.setObjectName("checkBox_TreatmentAttitudeActive")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeActive, 2, 1, 1, 1)
        self.checkBox_ReabilitationEPI = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationEPI.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationEPI.setObjectName("checkBox_ReabilitationEPI")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationEPI, 0, 4, 1, 1)
        self.radioButton_ReabilitationHigh = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ReabilitationHigh.setStyleSheet("background-color: rgb(247, 224, 255);")
        self.radioButton_ReabilitationHigh.setObjectName("radioButton_ReabilitationHigh")
        self.buttonGroup_5.addButton(self.radioButton_ReabilitationHigh)
        self.gridLayout_7.addWidget(self.radioButton_ReabilitationHigh, 0, 1, 1, 1)
        self.radioButton_TreatmentMotivationHigh = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TreatmentMotivationHigh.setStyleSheet("background-color: rgb(255, 221, 230);")
        self.radioButton_TreatmentMotivationHigh.setObjectName("radioButton_TreatmentMotivationHigh")
        self.buttonGroup_7.addButton(self.radioButton_TreatmentMotivationHigh)
        self.gridLayout_7.addWidget(self.radioButton_TreatmentMotivationHigh, 4, 1, 1, 1)
        self.checkBox_TreatmentAttitudeNotDisciplined = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeNotDisciplined.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeNotDisciplined.setObjectName("checkBox_TreatmentAttitudeNotDisciplined")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeNotDisciplined, 3, 4, 1, 1)
        self.radioButton_TreatmentMotivationLow = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_TreatmentMotivationLow.setStyleSheet("background-color: rgb(255, 221, 230);")
        self.radioButton_TreatmentMotivationLow.setObjectName("radioButton_TreatmentMotivationLow")
        self.buttonGroup_7.addButton(self.radioButton_TreatmentMotivationLow)
        self.gridLayout_7.addWidget(self.radioButton_TreatmentMotivationLow, 4, 3, 1, 1)
        self.checkBox_ReabilitationPhychoStudy = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_ReabilitationPhychoStudy.setStyleSheet("background-color: rgb(255, 244, 222);")
        self.checkBox_ReabilitationPhychoStudy.setObjectName("checkBox_ReabilitationPhychoStudy")
        self.gridLayout_7.addWidget(self.checkBox_ReabilitationPhychoStudy, 1, 2, 1, 1)
        self.checkBox_TreatmentAttitudeDisciplined = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeDisciplined.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeDisciplined.setObjectName("checkBox_TreatmentAttitudeDisciplined")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeDisciplined, 3, 3, 1, 1)
        self.checkBox_TreatmentAttitudeDeviant = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_TreatmentAttitudeDeviant.setStyleSheet("background-color: rgb(195, 255, 158);")
        self.checkBox_TreatmentAttitudeDeviant.setObjectName("checkBox_TreatmentAttitudeDeviant")
        self.gridLayout_7.addWidget(self.checkBox_TreatmentAttitudeDeviant, 2, 4, 1, 1)
        self.radioButton_ReabilitationMedium = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_ReabilitationMedium.setStyleSheet("background-color: rgb(247, 224, 255);")
        self.radioButton_ReabilitationMedium.setObjectName("radioButton_ReabilitationMedium")
        self.buttonGroup_5.addButton(self.radioButton_ReabilitationMedium)
        self.gridLayout_7.addWidget(self.radioButton_ReabilitationMedium, 0, 2, 1, 1)
        self.label_Reabilitation = QtWidgets.QLabel(self.centralwidget)
        self.label_Reabilitation.setStyleSheet("background-color: rgb(247, 224, 255);")
        self.label_Reabilitation.setWordWrap(True)
        self.label_Reabilitation.setObjectName("label_Reabilitation")
        self.gridLayout_7.addWidget(self.label_Reabilitation, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 6, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_SaveChanges = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveChanges.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveChanges.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 63, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 255, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_SaveChanges.setPalette(palette)
        self.pushButton_SaveChanges.setStyleSheet("background-color: rgb(184, 255, 190);")
        self.pushButton_SaveChanges.setObjectName("pushButton_SaveChanges")
        self.gridLayout_2.addWidget(self.pushButton_SaveChanges, 0, 1, 1, 1)
        self.pushButton_GoBack = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_GoBack.sizePolicy().hasHeightForWidth())
        self.pushButton_GoBack.setSizePolicy(sizePolicy)
        self.pushButton_GoBack.setStyleSheet("background-color:rgb(255, 135, 137);\n"
"")
        self.pushButton_GoBack.setObjectName("pushButton_GoBack")
        self.gridLayout_2.addWidget(self.pushButton_GoBack, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 7, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 5, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 3, 0, 1, 1)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_ClinicalDiagnosis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ClinicalDiagnosis.setObjectName("lineEdit_ClinicalDiagnosis")
        self.gridLayout_12.addWidget(self.lineEdit_ClinicalDiagnosis, 0, 9, 1, 1)
        self.label_ClinicalDiagnosis = QtWidgets.QLabel(self.centralwidget)
        self.label_ClinicalDiagnosis.setWordWrap(True)
        self.label_ClinicalDiagnosis.setObjectName("label_ClinicalDiagnosis")
        self.gridLayout_12.addWidget(self.label_ClinicalDiagnosis, 0, 8, 1, 1)
        self.lineEdit_OurMainDiagnosis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OurMainDiagnosis.setObjectName("lineEdit_OurMainDiagnosis")
        self.gridLayout_12.addWidget(self.lineEdit_OurMainDiagnosis, 0, 6, 1, 1)
        self.label_MainDiagnosisAnotherDepartment = QtWidgets.QLabel(self.centralwidget)
        self.label_MainDiagnosisAnotherDepartment.setObjectName("label_MainDiagnosisAnotherDepartment")
        self.gridLayout_12.addWidget(self.label_MainDiagnosisAnotherDepartment, 0, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_12.addWidget(self.line_8, 0, 3, 1, 1)
        self.lineEdit_MainDiagnosisAnotherDepartment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MainDiagnosisAnotherDepartment.setObjectName("lineEdit_MainDiagnosisAnotherDepartment")
        self.gridLayout_12.addWidget(self.lineEdit_MainDiagnosisAnotherDepartment, 0, 2, 1, 1)
        self.label_OurMainDiagnosis = QtWidgets.QLabel(self.centralwidget)
        self.label_OurMainDiagnosis.setObjectName("label_OurMainDiagnosis")
        self.gridLayout_12.addWidget(self.label_OurMainDiagnosis, 0, 5, 1, 1)
        self.label_DiagnosisFromAnotherDepartment = QtWidgets.QLabel(self.centralwidget)
        self.label_DiagnosisFromAnotherDepartment.setWordWrap(True)
        self.label_DiagnosisFromAnotherDepartment.setObjectName("label_DiagnosisFromAnotherDepartment")
        self.gridLayout_12.addWidget(self.label_DiagnosisFromAnotherDepartment, 0, 0, 1, 1)
        self.lineEdit_AdditionalDiagnosisAnotherDepartment = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AdditionalDiagnosisAnotherDepartment.setObjectName("lineEdit_AdditionalDiagnosisAnotherDepartment")
        self.gridLayout_12.addWidget(self.lineEdit_AdditionalDiagnosisAnotherDepartment, 1, 2, 1, 1)
        self.lineEdit_FinalDiagnosis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_FinalDiagnosis.setObjectName("lineEdit_FinalDiagnosis")
        self.gridLayout_12.addWidget(self.lineEdit_FinalDiagnosis, 1, 9, 1, 1)
        self.label_OurDiagnosis = QtWidgets.QLabel(self.centralwidget)
        self.label_OurDiagnosis.setWordWrap(True)
        self.label_OurDiagnosis.setObjectName("label_OurDiagnosis")
        self.gridLayout_12.addWidget(self.label_OurDiagnosis, 0, 4, 1, 1)
        self.lineEdit_OurAdditionalDiagnosis = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_OurAdditionalDiagnosis.setObjectName("lineEdit_OurAdditionalDiagnosis")
        self.gridLayout_12.addWidget(self.lineEdit_OurAdditionalDiagnosis, 1, 6, 1, 1)
        self.label_OurAdditionalDiagnosis = QtWidgets.QLabel(self.centralwidget)
        self.label_OurAdditionalDiagnosis.setObjectName("label_OurAdditionalDiagnosis")
        self.gridLayout_12.addWidget(self.label_OurAdditionalDiagnosis, 1, 5, 1, 1)
        self.label_FinalDiagnosis = QtWidgets.QLabel(self.centralwidget)
        self.label_FinalDiagnosis.setWordWrap(True)
        self.label_FinalDiagnosis.setObjectName("label_FinalDiagnosis")
        self.gridLayout_12.addWidget(self.label_FinalDiagnosis, 1, 8, 1, 1)
        self.label_AdditionalDiagnosisAnotherDepartment = QtWidgets.QLabel(self.centralwidget)
        self.label_AdditionalDiagnosisAnotherDepartment.setObjectName("label_AdditionalDiagnosisAnotherDepartment")
        self.gridLayout_12.addWidget(self.label_AdditionalDiagnosisAnotherDepartment, 1, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_12.addWidget(self.line_9, 1, 7, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_12.addWidget(self.line_10, 0, 7, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_12.addWidget(self.line_11, 1, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_12, 4, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setRowStretch(0, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_MoveFromOrganization, self.lineEdit_MoveFromDepartment)
        MainWindow.setTabOrder(self.lineEdit_MoveFromDepartment, self.lineEdit_MoveFromDoctor)
        MainWindow.setTabOrder(self.lineEdit_MoveFromDoctor, self.dateTimeEdit_MoveFromDateTime)
        MainWindow.setTabOrder(self.dateTimeEdit_MoveFromDateTime, self.comboBox_CurrentDoctor)
        MainWindow.setTabOrder(self.comboBox_CurrentDoctor, self.comboBox_MoveToOrganization)
        MainWindow.setTabOrder(self.comboBox_MoveToOrganization, self.lineEdit_MoveToDepatment)
        MainWindow.setTabOrder(self.lineEdit_MoveToDepatment, self.lineEdit_MoveToDoctor)
        MainWindow.setTabOrder(self.lineEdit_MoveToDoctor, self.dateEdit_MoveToDate)
        MainWindow.setTabOrder(self.dateEdit_MoveToDate, self.lineEdit_PatientLastName)
        MainWindow.setTabOrder(self.lineEdit_PatientLastName, self.lineEdit_PatientFirstName)
        MainWindow.setTabOrder(self.lineEdit_PatientFirstName, self.lineEdit_PatientPatronymic)
        MainWindow.setTabOrder(self.lineEdit_PatientPatronymic, self.lineEdit_PassportID)
        MainWindow.setTabOrder(self.lineEdit_PassportID, self.lineEdit_SnilsID)
        MainWindow.setTabOrder(self.lineEdit_SnilsID, self.lineEdit_OmsID)
        MainWindow.setTabOrder(self.lineEdit_OmsID, self.dateEdit_PatientBirthDate)
        MainWindow.setTabOrder(self.dateEdit_PatientBirthDate, self.radioButton_Female)
        MainWindow.setTabOrder(self.radioButton_Female, self.radioButton_Male)
        MainWindow.setTabOrder(self.radioButton_Male, self.lineEdit_DrugIntolerance)
        MainWindow.setTabOrder(self.lineEdit_DrugIntolerance, self.radioButton_TypeK)
        MainWindow.setTabOrder(self.radioButton_TypeK, self.radioButton_TypeADN)
        MainWindow.setTabOrder(self.radioButton_TypeADN, self.radioButton_TypeD)
        MainWindow.setTabOrder(self.radioButton_TypeD, self.radioButton_TypeUnknown)
        MainWindow.setTabOrder(self.radioButton_TypeUnknown, self.dateEdit_FLGDate)
        MainWindow.setTabOrder(self.dateEdit_FLGDate, self.comboBox_WorkStatus)
        MainWindow.setTabOrder(self.comboBox_WorkStatus, self.lineEdit_WorkStudy)
        MainWindow.setTabOrder(self.lineEdit_WorkStudy, self.radioButton_GroupM1)
        MainWindow.setTabOrder(self.radioButton_GroupM1, self.radioButton_GroupM2)
        MainWindow.setTabOrder(self.radioButton_GroupM2, self.radioButton_GroupM3)
        MainWindow.setTabOrder(self.radioButton_GroupM3, self.radioButton_GroupM4)
        MainWindow.setTabOrder(self.radioButton_GroupM4, self.radioButton_GroupImmobile)
        MainWindow.setTabOrder(self.radioButton_GroupImmobile, self.radioButton_DisabilityGroup0)
        MainWindow.setTabOrder(self.radioButton_DisabilityGroup0, self.radioButton_DisabilityGroupUnknown)
        MainWindow.setTabOrder(self.radioButton_DisabilityGroupUnknown, self.radioButton_DisabilityGroup1)
        MainWindow.setTabOrder(self.radioButton_DisabilityGroup1, self.radioButton_DisabilityGroup2)
        MainWindow.setTabOrder(self.radioButton_DisabilityGroup2, self.radioButton_DisabilityGroup3)
        MainWindow.setTabOrder(self.radioButton_DisabilityGroup3, self.lineEdit_CityMain)
        MainWindow.setTabOrder(self.lineEdit_CityMain, self.comboBox_TypeOfRoadMain)
        MainWindow.setTabOrder(self.comboBox_TypeOfRoadMain, self.lineEdit_RoadMain)
        MainWindow.setTabOrder(self.lineEdit_RoadMain, self.lineEdit_HomeMain)
        MainWindow.setTabOrder(self.lineEdit_HomeMain, self.lineEdit_BuildingMain)
        MainWindow.setTabOrder(self.lineEdit_BuildingMain, self.lineEdit_ApartmentNumberMain)
        MainWindow.setTabOrder(self.lineEdit_ApartmentNumberMain, self.lineEdit_EntranceMain)
        MainWindow.setTabOrder(self.lineEdit_EntranceMain, self.lineEdit_FloorMain)
        MainWindow.setTabOrder(self.lineEdit_FloorMain, self.lineEdit_CodeMain)
        MainWindow.setTabOrder(self.lineEdit_CodeMain, self.lineEdit_HomeTelephoneNumberMain)
        MainWindow.setTabOrder(self.lineEdit_HomeTelephoneNumberMain, self.lineEdit_MobilePhoneNumberMain)
        MainWindow.setTabOrder(self.lineEdit_MobilePhoneNumberMain, self.lineEdit_CityReg)
        MainWindow.setTabOrder(self.lineEdit_CityReg, self.comboBox_TypeOfRoadReg)
        MainWindow.setTabOrder(self.comboBox_TypeOfRoadReg, self.lineEdit_RoadReg)
        MainWindow.setTabOrder(self.lineEdit_RoadReg, self.lineEdit_HomeReg)
        MainWindow.setTabOrder(self.lineEdit_HomeReg, self.lineEdit_BuildingReg)
        MainWindow.setTabOrder(self.lineEdit_BuildingReg, self.lineEdit_ApartmentNumberReg)
        MainWindow.setTabOrder(self.lineEdit_ApartmentNumberReg, self.comboBox_ProxyType)
        MainWindow.setTabOrder(self.comboBox_ProxyType, self.lineEdit_ProxyLastName)
        MainWindow.setTabOrder(self.lineEdit_ProxyLastName, self.lineEdit_ProxyFirstName)
        MainWindow.setTabOrder(self.lineEdit_ProxyFirstName, self.lineEdit_ProxyPatronymic)
        MainWindow.setTabOrder(self.lineEdit_ProxyPatronymic, self.lineEdit_ProxyTelephoneNumber1)
        MainWindow.setTabOrder(self.lineEdit_ProxyTelephoneNumber1, self.lineEdit_ProxyTelephoneNumber2)
        MainWindow.setTabOrder(self.lineEdit_ProxyTelephoneNumber2, self.lineEdit_ProxyTelephoneNumber3)
        MainWindow.setTabOrder(self.lineEdit_ProxyTelephoneNumber3, self.lineEdit_ProxyCommentaries)
        MainWindow.setTabOrder(self.lineEdit_ProxyCommentaries, self.lineEdit_MainDiagnosisAnotherDepartment)
        MainWindow.setTabOrder(self.lineEdit_MainDiagnosisAnotherDepartment, self.lineEdit_OurMainDiagnosis)
        MainWindow.setTabOrder(self.lineEdit_OurMainDiagnosis, self.lineEdit_ClinicalDiagnosis)
        MainWindow.setTabOrder(self.lineEdit_ClinicalDiagnosis, self.radioButton_ReabilitationHigh)
        MainWindow.setTabOrder(self.radioButton_ReabilitationHigh, self.radioButton_ReabilitationMedium)
        MainWindow.setTabOrder(self.radioButton_ReabilitationMedium, self.radioButton_ReabilitationLow)
        MainWindow.setTabOrder(self.radioButton_ReabilitationLow, self.checkBox_ReabilitationEPI)
        MainWindow.setTabOrder(self.checkBox_ReabilitationEPI, self.checkBox_ReabilitationIndividual)
        MainWindow.setTabOrder(self.checkBox_ReabilitationIndividual, self.checkBox_ReabilitationFamily)
        MainWindow.setTabOrder(self.checkBox_ReabilitationFamily, self.checkBox_ReabilitationPhychoStudy)
        MainWindow.setTabOrder(self.checkBox_ReabilitationPhychoStudy, self.checkBox_ReabilitationMotivation)
        MainWindow.setTabOrder(self.checkBox_ReabilitationMotivation, self.checkBox_ReabilitationTBN)
        MainWindow.setTabOrder(self.checkBox_ReabilitationTBN, self.checkBox_TreatmentAttitudeActive)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeActive, self.checkBox_TreatmentAttitudeNeutral)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeNeutral, self.checkBox_TreatmentAttitudePassive)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudePassive, self.checkBox_TreatmentAttitudeDeviant)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeDeviant, self.checkBox_TreatmentAttitudeIndifferent)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeIndifferent, self.checkBox_TreatmentAttitudeNegativity)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeNegativity, self.checkBox_TreatmentAttitudeDisciplined)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeDisciplined, self.checkBox_TreatmentAttitudeNotDisciplined)
        MainWindow.setTabOrder(self.checkBox_TreatmentAttitudeNotDisciplined, self.radioButton_TreatmentMotivationHigh)
        MainWindow.setTabOrder(self.radioButton_TreatmentMotivationHigh, self.radioButton_TreatmentMotivationMedium)
        MainWindow.setTabOrder(self.radioButton_TreatmentMotivationMedium, self.radioButton_TreatmentMotivationLow)
        MainWindow.setTabOrder(self.radioButton_TreatmentMotivationLow, self.lineEdit_AdditionalDiagnosisAnotherDepartment)
        MainWindow.setTabOrder(self.lineEdit_AdditionalDiagnosisAnotherDepartment, self.lineEdit_OurAdditionalDiagnosis)
        MainWindow.setTabOrder(self.lineEdit_OurAdditionalDiagnosis, self.lineEdit_FinalDiagnosis)
        MainWindow.setTabOrder(self.lineEdit_FinalDiagnosis, self.pushButton_GoBack)
        MainWindow.setTabOrder(self.pushButton_GoBack, self.pushButton_SaveChanges)
        MainWindow.setTabOrder(self.pushButton_SaveChanges, self.lineEdit_YearOfHistory)
        MainWindow.setTabOrder(self.lineEdit_YearOfHistory, self.lineEdit_HistoryNumber)
        MainWindow.setTabOrder(self.lineEdit_HistoryNumber, self.lineEdit_DaysInOIOPP)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_HistoryNumber.setText(_translate("MainWindow", "№ИБ"))
        self.label_MoveFrom.setText(_translate("MainWindow", "Поступил из"))
        self.comboBox_MoveFromOrganization.setItemText(1, _translate("MainWindow", "ПКБ №4"))
        self.comboBox_MoveFromOrganization.setItemText(2, _translate("MainWindow", "ПНД №17"))
        self.comboBox_MoveFromOrganization.setItemText(3, _translate("MainWindow", "Обр.самост."))
        self.comboBox_MoveFromOrganization.setItemText(4, _translate("MainWindow", "ПКБ №1"))
        self.label_MoveFromDepartment.setText(_translate("MainWindow", "отделение"))
        self.label_MoveFromDoctor.setText(_translate("MainWindow", "врач"))
        self.label_CurrentDoctor.setText(_translate("MainWindow", "Лечащий Врач:"))
        self.comboBox_CurrentDoctor.setItemText(1, _translate("MainWindow", "Болдырев А.Н."))
        self.comboBox_CurrentDoctor.setItemText(2, _translate("MainWindow", "Бакланов Д.В."))
        self.comboBox_CurrentDoctor.setItemText(3, _translate("MainWindow", "Фишер Л.Р."))
        self.comboBox_CurrentDoctor.setItemText(4, _translate("MainWindow", "Бабайлов А.А."))
        self.comboBox_CurrentDoctor.setItemText(5, _translate("MainWindow", "Говенько А.А."))
        self.label_DaysInOIOPP.setText(_translate("MainWindow", "Количество к/д"))
        self.label_MovTo.setText(_translate("MainWindow", "Выписан в"))
        self.comboBox_MoveToOrganization.setItemText(1, _translate("MainWindow", "ПКБ №4"))
        self.comboBox_MoveToOrganization.setItemText(2, _translate("MainWindow", "ПНД №17"))
        self.comboBox_MoveToOrganization.setItemText(3, _translate("MainWindow", "ПКБ №1"))
        self.label_MoveToDepartment.setText(_translate("MainWindow", "отделение"))
        self.label_MoveToDoctor.setText(_translate("MainWindow", "врач"))
        self.lineEdit_YearOfHistory.setText(_translate("MainWindow", "20"))
        self.label_Slash.setText(_translate("MainWindow", "/"))
        self.label_PatientLastName.setText(_translate("MainWindow", "Фамилия"))
        self.label_PatientBirthDate.setText(_translate("MainWindow", "Дата рождения"))
        self.label_PatientPatronymic.setText(_translate("MainWindow", "Отчество"))
        self.label_TypeOFObservation.setText(_translate("MainWindow", "Вид наблюдения"))
        self.label_FLGDate.setText(_translate("MainWindow", "ФЛГ от"))
        self.label_PassportID.setText(_translate("MainWindow", "Паспорт"))
        self.label_PatientFirstName.setText(_translate("MainWindow", "Имя"))
        self.label_DrugIntolerance.setText(_translate("MainWindow", "Неп. лекарств:"))
        self.lineEdit_DrugIntolerance.setText(_translate("MainWindow", "без особенностей"))
        self.label_SnilsID.setText(_translate("MainWindow", "СНИЛС"))
        self.radioButton_TypeK.setText(_translate("MainWindow", "К"))
        self.radioButton_TypeADN.setText(_translate("MainWindow", "АДН"))
        self.radioButton_TypeD.setText(_translate("MainWindow", "Д"))
        self.radioButton_TypeUnknown.setText(_translate("MainWindow", "неизвестно"))
        self.label_OmsID.setText(_translate("MainWindow", "ОМС"))
        self.radioButton_Male.setText(_translate("MainWindow", "М"))
        self.radioButton_Female.setText(_translate("MainWindow", "Ж"))
        self.comboBox_WorkStatus.setItemText(0, _translate("MainWindow", "Не работает"))
        self.comboBox_WorkStatus.setItemText(1, _translate("MainWindow", "Работает"))
        self.comboBox_WorkStatus.setItemText(2, _translate("MainWindow", "Учится"))
        self.label_WorkStudy.setText(_translate("MainWindow", "Место работы, учебы, профессия, должность"))
        self.label_MobilityGroup.setText(_translate("MainWindow", "Группа\n"
"мобильности"))
        self.radioButton_GroupM1.setText(_translate("MainWindow", "М1"))
        self.label_GroupM1.setText(_translate("MainWindow", "люди, не имеющие ограничений по мобильности, в том числе с дефектами слуха"))
        self.radioButton_GroupM2.setText(_translate("MainWindow", "М2"))
        self.label_GroupM2.setText(_translate("MainWindow", "немощные люди, мобильность которых снижена из-за старения организма (инвалиды по старости); инвалиды на протезах; инвалиды с недостатками зрения, пользующиеся белой тростью; люди с психическими отклонениями"))
        self.radioButton_GroupM3.setText(_translate("MainWindow", "М3"))
        self.label_GroupM3.setText(_translate("MainWindow", "инвалиды, использующие при движении дополнительные опоры (костыли, палки)"))
        self.radioButton_GroupM4.setText(_translate("MainWindow", "М4"))
        self.label_GroupM4.setText(_translate("MainWindow", "инвалиды, передвигающиеся на креслах-колясках, приводимых в движение вручную"))
        self.radioButton_GroupImmobile.setText(_translate("MainWindow", "Немобильные\n"
"пациенты"))
        self.label_GroupImmobile.setText(_translate("MainWindow", "пациенты, не способные к самостоятельному передвижению по состоянию здоровья, эвакуация которых возможна на носилках либо каталках"))
        self.label_DisabilityGroup.setText(_translate("MainWindow", "Инвалидность"))
        self.radioButton_DisabilityGroup0.setText(_translate("MainWindow", "нет"))
        self.radioButton_DisabilityGroupUnknown.setText(_translate("MainWindow", "неизвестно"))
        self.radioButton_DisabilityGroup1.setText(_translate("MainWindow", "I группа"))
        self.radioButton_DisabilityGroup2.setText(_translate("MainWindow", "II группа"))
        self.radioButton_DisabilityGroup3.setText(_translate("MainWindow", "III группа"))
        self.label_Building.setText(_translate("MainWindow", "строение/корпус"))
        self.comboBox_TypeOfRoadMain.setItemText(0, _translate("MainWindow", "улица"))
        self.comboBox_TypeOfRoadMain.setItemText(1, _translate("MainWindow", "шоссе"))
        self.comboBox_TypeOfRoadMain.setItemText(2, _translate("MainWindow", "проезд"))
        self.comboBox_TypeOfRoadMain.setItemText(3, _translate("MainWindow", "проспект"))
        self.comboBox_TypeOfRoadMain.setItemText(4, _translate("MainWindow", "тупик"))
        self.comboBox_TypeOfRoadMain.setItemText(5, _translate("MainWindow", "переулок"))
        self.comboBox_TypeOfRoadMain.setItemText(6, _translate("MainWindow", "бульвар"))
        self.label_Home.setText(_translate("MainWindow", "дом"))
        self.label_ApartmentNumber.setText(_translate("MainWindow", "квартира"))
        self.label_CurrentAdress.setText(_translate("MainWindow", "Адрес факт."))
        self.lineEdit_CityMain.setText(_translate("MainWindow", "г.Москва"))
        self.label_Entrance.setText(_translate("MainWindow", "подъезд"))
        self.label_AdressOfRegistration.setText(_translate("MainWindow", "Адрес проп.\n"
"если отлич."))
        self.label_Floor.setText(_translate("MainWindow", "этаж"))
        self.comboBox_TypeOfRoadReg.setItemText(0, _translate("MainWindow", "улица"))
        self.comboBox_TypeOfRoadReg.setItemText(1, _translate("MainWindow", "шоссе"))
        self.comboBox_TypeOfRoadReg.setItemText(2, _translate("MainWindow", "проезд"))
        self.comboBox_TypeOfRoadReg.setItemText(3, _translate("MainWindow", "проспект"))
        self.comboBox_TypeOfRoadReg.setItemText(4, _translate("MainWindow", "тупик"))
        self.comboBox_TypeOfRoadReg.setItemText(5, _translate("MainWindow", "переулок"))
        self.comboBox_TypeOfRoadReg.setItemText(6, _translate("MainWindow", "бульвар"))
        self.label_CodeMain.setText(_translate("MainWindow", "домофон"))
        self.label_HomeReg.setText(_translate("MainWindow", "дом"))
        self.label_BuildingReg.setText(_translate("MainWindow", "строение/корпус"))
        self.label_ApartmentNumberReg.setText(_translate("MainWindow", "квартира"))
        self.label_MobilePhoneNumber.setText(_translate("MainWindow", "тел. сот"))
        self.label_HomeTelephoneNumber.setText(_translate("MainWindow", "тел. дом"))
        self.label_ProxyTelephoneNumber2.setText(_translate("MainWindow", "телефон"))
        self.label_ProxyPatronymic.setText(_translate("MainWindow", "Отчество"))
        self.label_ProxyFirstName.setText(_translate("MainWindow", "Имя"))
        self.label_ProxyTelephoneNumber1.setText(_translate("MainWindow", "телефон"))
        self.comboBox_ProxyType.setItemText(1, _translate("MainWindow", "супруг(а)"))
        self.comboBox_ProxyType.setItemText(2, _translate("MainWindow", "дочь"))
        self.comboBox_ProxyType.setItemText(3, _translate("MainWindow", "сын"))
        self.comboBox_ProxyType.setItemText(4, _translate("MainWindow", "племянник"))
        self.comboBox_ProxyType.setItemText(5, _translate("MainWindow", "племянница"))
        self.comboBox_ProxyType.setItemText(6, _translate("MainWindow", "внук"))
        self.comboBox_ProxyType.setItemText(7, _translate("MainWindow", "внучка"))
        self.comboBox_ProxyType.setItemText(8, _translate("MainWindow", "брат"))
        self.comboBox_ProxyType.setItemText(9, _translate("MainWindow", "сестра"))
        self.comboBox_ProxyType.setItemText(10, _translate("MainWindow", "отец"))
        self.comboBox_ProxyType.setItemText(11, _translate("MainWindow", "мать"))
        self.comboBox_ProxyType.setItemText(12, _translate("MainWindow", "тётя"))
        self.comboBox_ProxyType.setItemText(13, _translate("MainWindow", "дядя"))
        self.comboBox_ProxyType.setItemText(14, _translate("MainWindow", "дедушка"))
        self.comboBox_ProxyType.setItemText(15, _translate("MainWindow", "бабушка"))
        self.comboBox_ProxyType.setItemText(16, _translate("MainWindow", "соц. раб."))
        self.comboBox_ProxyType.setItemText(17, _translate("MainWindow", "сосед(ка)"))
        self.label_ProxyLastName.setText(_translate("MainWindow", "Фамилия"))
        self.label_ProxyTelephoneNumber3.setText(_translate("MainWindow", "телефон"))
        self.label_ProxyCommentaries.setText(_translate("MainWindow", "Комментарии"))
        self.checkBox_ReabilitationFamily.setText(_translate("MainWindow", "Сем консультация"))
        self.checkBox_ReabilitationMotivation.setText(_translate("MainWindow", "Мотивац тренинг"))
        self.radioButton_TreatmentMotivationMedium.setText(_translate("MainWindow", "Средний"))
        self.label_TreatmentAttitude.setText(_translate("MainWindow", "Отношение к лечению:"))
        self.label_TreatmentMotivation.setText(_translate("MainWindow", "Мотивация к лечению:"))
        self.checkBox_ReabilitationIndividual.setText(_translate("MainWindow", "Индивидуальная консультация"))
        self.checkBox_TreatmentAttitudeNegativity.setText(_translate("MainWindow", "Негативное"))
        self.checkBox_TreatmentAttitudeNeutral.setText(_translate("MainWindow", "Нейтральное"))
        self.checkBox_TreatmentAttitudePassive.setText(_translate("MainWindow", "Пассивное"))
        self.checkBox_TreatmentAttitudeIndifferent.setText(_translate("MainWindow", "Безразличное"))
        self.radioButton_ReabilitationLow.setText(_translate("MainWindow", "Низкий"))
        self.checkBox_ReabilitationTBN.setText(_translate("MainWindow", "Тренинг быт навыков"))
        self.checkBox_TreatmentAttitudeActive.setText(_translate("MainWindow", "Активное"))
        self.checkBox_ReabilitationEPI.setText(_translate("MainWindow", "ЭПИ"))
        self.radioButton_ReabilitationHigh.setText(_translate("MainWindow", "Высокий"))
        self.radioButton_TreatmentMotivationHigh.setText(_translate("MainWindow", "Высокий"))
        self.checkBox_TreatmentAttitudeNotDisciplined.setText(_translate("MainWindow", "Недисциплинированное"))
        self.radioButton_TreatmentMotivationLow.setText(_translate("MainWindow", "Низкий"))
        self.checkBox_ReabilitationPhychoStudy.setText(_translate("MainWindow", "Психоб тренинг"))
        self.checkBox_TreatmentAttitudeDisciplined.setText(_translate("MainWindow", "Дисциплинированное"))
        self.checkBox_TreatmentAttitudeDeviant.setText(_translate("MainWindow", "Отклоняющееся"))
        self.radioButton_ReabilitationMedium.setText(_translate("MainWindow", "Средний"))
        self.label_Reabilitation.setText(_translate("MainWindow", "Реаб. потенциал:"))
        self.pushButton_SaveChanges.setText(_translate("MainWindow", "Сохранить изменения"))
        self.pushButton_GoBack.setText(_translate("MainWindow", "Вернуться назад"))
        self.lineEdit_ClinicalDiagnosis.setText(_translate("MainWindow", "F"))
        self.label_ClinicalDiagnosis.setText(_translate("MainWindow", "Диагноз Клинический"))
        self.lineEdit_OurMainDiagnosis.setText(_translate("MainWindow", "F"))
        self.label_MainDiagnosisAnotherDepartment.setText(_translate("MainWindow", "основной"))
        self.lineEdit_MainDiagnosisAnotherDepartment.setText(_translate("MainWindow", "F"))
        self.label_OurMainDiagnosis.setText(_translate("MainWindow", "основной"))
        self.label_DiagnosisFromAnotherDepartment.setText(_translate("MainWindow", "Диагноз направившего учреждения"))
        self.lineEdit_FinalDiagnosis.setText(_translate("MainWindow", "F"))
        self.label_OurDiagnosis.setText(_translate("MainWindow", "Диагноз при поступлении"))
        self.label_OurAdditionalDiagnosis.setText(_translate("MainWindow", "дополнительный"))
        self.label_FinalDiagnosis.setText(_translate("MainWindow", "Диагноз заключительный"))
        self.label_AdditionalDiagnosisAnotherDepartment.setText(_translate("MainWindow", "дополнительный"))
