# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_SearchLine = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SearchLine.setObjectName("lineEdit_SearchLine")
        self.verticalLayout_2.addWidget(self.lineEdit_SearchLine)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 250, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_CaseHistory = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CaseHistory.setCheckable(True)
        self.pushButton_CaseHistory.setChecked(False)
        self.pushButton_CaseHistory.setFlat(True)
        self.pushButton_CaseHistory.setObjectName("pushButton_CaseHistory")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_CaseHistory)
        self.verticalLayout_3.addWidget(self.pushButton_CaseHistory)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_EditingHistory = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_EditingHistory.setObjectName("pushButton_EditingHistory")
        self.horizontalLayout_2.addWidget(self.pushButton_EditingHistory)
        self.pushButton_DeleteHistory = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_DeleteHistory.setStyleSheet("background-color: rgb(255, 152, 176);")
        self.pushButton_DeleteHistory.setObjectName("pushButton_DeleteHistory")
        self.horizontalLayout_2.addWidget(self.pushButton_DeleteHistory)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_CreateNextHistory = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_CreateNextHistory.setObjectName("pushButton_CreateNextHistory")
        self.verticalLayout_2.addWidget(self.pushButton_CreateNextHistory)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.calendarWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_SummaryMoveFromTo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SummaryMoveFromTo.setObjectName("pushButton_SummaryMoveFromTo")
        self.verticalLayout_5.addWidget(self.pushButton_SummaryMoveFromTo)
        self.pushButton_StatisticMonth = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StatisticMonth.setObjectName("pushButton_StatisticMonth")
        self.verticalLayout_5.addWidget(self.pushButton_StatisticMonth)
        self.pushButton_MonthReport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MonthReport.setObjectName("pushButton_MonthReport")
        self.verticalLayout_5.addWidget(self.pushButton_MonthReport)
        self.pushButton_TablePPB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_TablePPB.setObjectName("pushButton_TablePPB")
        self.verticalLayout_5.addWidget(self.pushButton_TablePPB)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Cover = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Cover.setObjectName("pushButton_Cover")
        self.gridLayout.addWidget(self.pushButton_Cover, 0, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 4, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 4, 4, 1, 1)
        self.pushButton_Referral = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Referral.setObjectName("pushButton_Referral")
        self.gridLayout.addWidget(self.pushButton_Referral, 1, 2, 1, 1)
        self.checkBox_Protector = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Protector.setObjectName("checkBox_Protector")
        self.gridLayout.addWidget(self.checkBox_Protector, 5, 4, 1, 1)
        self.pushButton_Repeating = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Repeating.setObjectName("pushButton_Repeating")
        self.gridLayout.addWidget(self.pushButton_Repeating, 5, 2, 1, 1)
        self.pushButton_SecondPPB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SecondPPB.setObjectName("pushButton_SecondPPB")
        self.gridLayout.addWidget(self.pushButton_SecondPPB, 4, 3, 1, 1)
        self.pushButton_FirstPPB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FirstPPB.setObjectName("pushButton_FirstPPB")
        self.gridLayout.addWidget(self.pushButton_FirstPPB, 2, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_CaseHistory.setText(_translate("MainWindow", "№ИБ, ФИО"))
        self.pushButton_EditingHistory.setText(_translate("MainWindow", "Редактировать историю"))
        self.pushButton_DeleteHistory.setText(_translate("MainWindow", "Удалить историю"))
        self.pushButton_CreateNextHistory.setText(_translate("MainWindow", "Создать новую историю болезни"))
        self.pushButton_SummaryMoveFromTo.setText(_translate("MainWindow", "Сводка"))
        self.pushButton_StatisticMonth.setText(_translate("MainWindow", "Движение\n"
" за месяц"))
        self.pushButton_MonthReport.setText(_translate("MainWindow", "Отчет за месяц"))
        self.pushButton_TablePPB.setText(_translate("MainWindow", "ППБ таблица"))
        self.pushButton_Cover.setText(_translate("MainWindow", "Обложка"))
        self.pushButton_3.setText(_translate("MainWindow", "Резерв"))
        self.pushButton_5.setText(_translate("MainWindow", "Резерв"))
        self.pushButton_6.setText(_translate("MainWindow", "Резерв"))
        self.pushButton_Referral.setText(_translate("MainWindow", "Направление"))
        self.checkBox_Protector.setText(_translate("MainWindow", "предохранитель"))
        self.pushButton_Repeating.setText(_translate("MainWindow", "Повторное \n"
" поступление"))
        self.pushButton_SecondPPB.setText(_translate("MainWindow", "Повторное ППБ"))
        self.pushButton_FirstPPB.setText(_translate("MainWindow", "Первичное ППБ"))
